[tool.poetry]
name = "rip"
version = "0.1.0"
description = ""
authors = ["Andrew Duane <andrew.m.duane@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
wheel = "^0.35.1"
jsonschema = "^3.2.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
